spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    username: "root"
    password: ""
    url: "jdbc:mysql://127.0.0.1:3306/test"
    driver-class: com.mysql.jdbc.Driver
